# main.py — Generated by VIA for: Build me an IQ test app with 10 questions and score results
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

import os

app = FastAPI(
    title="Build Me An Iq Test App",
    description="Generated by VIA — Autonomous AI Digital Team",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

questions_data = [
    {"id": 1, "question": "What comes next: 2, 4, 8, 16, ?", "options": ["24","32","28","20"], "answer": "32", "category": "Pattern"},
    {"id": 2, "question": "All Bloops are Razzles, all Razzles are Lazzles. All Bloops are Lazzles?", "options": ["True","False"], "answer": "True", "category": "Logic"},
    {"id": 3, "question": "Odd one out: 3, 5, 11, 14, 23, 29?", "options": ["3","5","14","29"], "answer": "14", "category": "Numbers"},
    {"id": 4, "question": "5 + 3 × 2 = ?", "options": ["16","11","13","10"], "answer": "11", "category": "Numerical"},
    {"id": 5, "question": "Book:Reading :: Fork:?", "options": ["Cooking","Eating","Kitchen","Food"], "answer": "Eating", "category": "Verbal"},
]

@app.get("/")
def root():
    return {"app": "Build Me An Iq Test App", "status": "running", "generated_by": "VIA"}

@app.get("/health")
def health():
    return {"status": "healthy"}


@app.get("/api/v1/questions")
def get_questions():
    return questions_data

@app.post("/api/v1/submit")
def submit_score(payload: dict):
    score = payload.get("score", 0)
    total = payload.get("total", len(questions_data))
    pct   = round((score / total) * 100, 1) if total else 0
    if pct >= 90:   iq_level = "Genius (IQ 140+)"
    elif pct >= 80: iq_level = "Very Intelligent (IQ 120-139)"
    elif pct >= 70: iq_level = "Intelligent (IQ 110-119)"
    elif pct >= 60: iq_level = "Above Average (IQ 100-109)"
    else:           iq_level = "Average (IQ 90-99)"
    return {"score": score, "total": total, "percentage": pct, "iq_level": iq_level}

@app.get("/api/v1/items")
def get_items():
    return {"items": [], "total": 0}

@app.post("/api/v1/items")
def create_item(item: dict):
    return item

@app.get("/api/v1/items/{item_id}")
def get_item(item_id: int):
    raise HTTPException(status_code=404, detail="Item not found")

@app.put("/api/v1/items/{item_id}")
def update_item(item_id: int, update: dict):
    raise HTTPException(status_code=404, detail="Item not found")

@app.delete("/api/v1/items/{item_id}")
def delete_item(item_id: int):
    return {"deleted": item_id}

@app.get("/api/v1/stats")
def get_stats():
    return {"total": len(questions_data), "active": len(questions_data), "categories": list(set(q["category"] for q in questions_data))}


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", 8000))
    uvicorn.run("main:app", host="0.0.0.0", port=port, reload=False)
