// src/App.jsx — Generated by VIA for: Build me an IQ test app with 10 questions and score results
import { useState, useEffect } from "react";
import { toast, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { getItems, createItem, deleteItem } from "./api.js";

const GRADES = [
  { min:90, letter:"A+", color:"text-emerald-600 bg-emerald-50" },
  { min:80, letter:"A",  color:"text-emerald-600 bg-emerald-50" },
  { min:70, letter:"B",  color:"text-blue-600 bg-blue-50" },
  { min:60, letter:"C",  color:"text-amber-600 bg-amber-50" },
  { min:50, letter:"D",  color:"text-orange-600 bg-orange-50" },
  { min:0,  letter:"F",  color:"text-red-600 bg-red-50" },
];
const gradeInfo = (score) => GRADES.find(g => score >= g.min) || GRADES[GRADES.length-1];

const SAMPLE_STUDENTS = [
  { id:1, title:"Alice Johnson", roll:"001", math:92, science:88, english:95, history:79 },
  { id:2, title:"Bob Smith",     roll:"002", math:74, science:81, english:68, history:85 },
  { id:3, title:"Carol White",   roll:"003", math:56, science:63, english:72, history:60 },
];

export default function App() {
  const [students, setStudents] = useState(SAMPLE_STUDENTS);
  const [search, setSearch] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ title:"", roll:"", math:"", science:"", english:"", history:"" });
  const [loading, setLoading] = useState(false);
  const [sortBy, setSortBy] = useState("title");

  useEffect(() => {
    getItems().then(r => {
      const items = Array.isArray(r.data) ? r.data : r.data?.items ?? [];
      if (items.length) setStudents(items);
    }).catch(() => {});
  }, []);

  const avg = (s) => {
    const scores = [s.math, s.science, s.english, s.history].filter(x => x !== undefined && x !== "");
    return scores.length ? Math.round(scores.reduce((a,b) => a + Number(b), 0) / scores.length) : 0;
  };

  const filtered = students
    .filter(s => s.title?.toLowerCase().includes(search.toLowerCase()) || s.roll?.includes(search))
    .sort((a,b) => sortBy === "avg" ? avg(b) - avg(a) : a.title?.localeCompare(b.title));

  const classAvg = students.length ? Math.round(students.reduce((s,st) => s + avg(st), 0) / students.length) : 0;
  const passing  = students.filter(s => avg(s) >= 50).length;

  const handleAdd = async (e) => {
    e.preventDefault();
    if (!form.title.trim()) { toast.error("Student name required"); return; }
    setLoading(true);
    try {
      const res = await createItem({ ...form, status:"active" });
      const item = res.data?.item ?? res.data ?? { ...form, id: Date.now() };
      setStudents(prev => [...prev, item]);
      setShowForm(false); setForm({ title:"", roll:"", math:"", science:"", english:"", history:"" });
      toast.success("Student added!");
    } catch { setStudents(prev => [...prev, { ...form, id:Date.now() }]); setShowForm(false); } finally { setLoading(false); }
  };

  const handleDelete = (id) => {
    if (!confirm("Remove this student?")) return;
    setStudents(prev => prev.filter(s => (s.id ?? s._id) !== id));
    deleteItem(id).catch(() => {});
    toast.success("Student removed");
  };

  return (
    <div className="min-h-screen" style={{ backgroundColor: "#eef2ff" }}>
      <ToastContainer position="top-right" autoClose={3000} />
      <nav className="bg-white border-b border-gray-100 shadow-sm sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3"><span className="text-2xl">⚡</span><span className="font-bold text-gray-900">Build Me An Iq Test App With 10</span></div>
          <button onClick={() => setShowForm(true)} className="btn-primary">+ Add Student</button>
        </div>
      </nav>
      <main className="max-w-7xl mx-auto px-6 py-8 space-y-6">
        {/* Stats */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            ["Total Students", students.length, "👥"],
            ["Passing", passing, "✅"],
            ["Failing", students.length - passing, "⚠️"],
            ["Class Average", classAvg + "%", "📊"],
          ].map(([label, val, ic]) => (
            <div key={label} className="card text-center">
              <p className="text-2xl mb-1">{ic}</p>
              <p className="text-2xl font-bold text-gray-900">{val}</p>
              <p className="text-xs text-gray-500 mt-1">{label}</p>
            </div>
          ))}
        </div>

        {/* Controls */}
        <div className="flex flex-col sm:flex-row gap-3">
          <input className="input max-w-xs" placeholder="Search by name or roll…" value={search} onChange={e => setSearch(e.target.value)} />
          <select className="input max-w-xs" value={sortBy} onChange={e => setSortBy(e.target.value)}>
            <option value="title">Sort by Name</option>
            <option value="avg">Sort by Average</option>
          </select>
        </div>

        {/* Table */}
        <div className="card overflow-hidden p-0">
          <table className="w-full text-sm">
            <thead className="bg-gray-50 border-b border-gray-100">
              <tr>
                <th className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Roll</th>
                <th className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Name</th>
                <th className="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Math</th>
                <th className="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Science</th>
                <th className="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">English</th>
                <th className="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">History</th>
                <th className="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Average</th>
                <th className="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Grade</th>
                <th className="px-4 py-3 text-right text-xs font-semibold text-gray-500 uppercase">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {filtered.map(s => {
                const a = avg(s); const gi = gradeInfo(a);
                return (
                  <tr key={s.id ?? s._id} className="hover:bg-gray-50/50">
                    <td className="px-4 py-3 text-gray-500">{s.roll || "—"}</td>
                    <td className="px-4 py-3 font-medium text-gray-900">{s.title}</td>
                    {["math","science","english","history"].map(sub => (
                      <td key={sub} className="px-4 py-3 text-center text-gray-700">{s[sub] ?? "—"}</td>
                    ))}
                    <td className="px-4 py-3 text-center font-bold text-gray-900">{a}%</td>
                    <td className="px-4 py-3 text-center"><span className={`text-xs font-bold px-2 py-1 rounded-full ${gi.color}`}>{gi.letter}</span></td>
                    <td className="px-4 py-3 text-right"><button onClick={() => handleDelete(s.id ?? s._id)} className="text-xs px-2 py-1 bg-red-50 text-red-500 rounded-lg border border-red-100">Remove</button></td>
                  </tr>
                );
              })}
            </tbody>
          </table>
          <div className="px-4 py-3 bg-gray-50/50 border-t text-xs text-gray-400">{filtered.length} student{filtered.length !== 1 ? "s" : ""}</div>
        </div>
      </main>

      {showForm && (
        <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md p-6 space-y-4">
            <div className="flex justify-between items-center"><h2 className="text-xl font-bold">Add Student</h2><button onClick={() => setShowForm(false)} className="text-gray-400 hover:text-gray-600 text-xl">✕</button></div>
            <form onSubmit={handleAdd} className="space-y-3">
              <div className="grid grid-cols-2 gap-3">
                <input className="input" placeholder="Full name *" value={form.title} onChange={e => setForm({...form, title: e.target.value})} required />
                <input className="input" placeholder="Roll number" value={form.roll} onChange={e => setForm({...form, roll: e.target.value})} />
              </div>
              <div className="grid grid-cols-2 gap-3">
                {["math","science","english","history"].map(sub => (
                  <input key={sub} className="input" type="number" min="0" max="100"
                    placeholder={sub.charAt(0).toUpperCase() + sub.slice(1) + " score"}
                    value={form[sub]} onChange={e => setForm({...form, [sub]: e.target.value})} />
                ))}
              </div>
              <div className="flex gap-3 pt-1"><button type="submit" className="btn-primary" disabled={loading}>{loading ? "Saving…" : "Add"}</button><button type="button" onClick={() => setShowForm(false)} className="btn-secondary">Cancel</button></div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
